apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pomodoro.fullname" . }}
  labels:
    {{- include "pomodoro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pomodoro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pomodoro.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pomodoro.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: html-content
          configMap:
            name: {{ include "pomodoro.fullname" . }}-html
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
