apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pomodoro.fullname" . }}
  labels:
    {{- include "pomodoro.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
