apiVersion: v1
kind: Service
metadata:
  name: {{ include "pomodoro.fullname" . }}
  labels:
    {{- include "pomodoro.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "pomodoro.selectorLabels" . | nindent 4 }}
